INSERT INTO `pays_facts_tips` (`id`, `name`, `language`, `religion`, `visa`, `climate`, `currency`, `power_plugs`, `capital`, `apps`, `flights`, `safety`, `budget`) VALUES
(22, 'Spain', 'Spanish', 'Christianity ', 'Shengen Area rules apply', 'Mediterranean; hot, dry summers & mild winters', 'Euro (EUR)', 'Type C / F', 'Madrid', 'El Tiempo',
 ' The three main airports in Spain are Madrid (MAD), Barcelona (BCN) and Palma de Mallorca (PMI), which have direct international flights from many countries in Europe and beyond.',
  'Spain is generally a safe place to travel, with a very low violent crime rate of 0.6 per 100k inhabitants (90% lower than the global average). It\'s one of the safest countries in the world. With that said, pickpocketing and theft are notoriously common in Barcelona. Practice situational awareness and keep your hands in your pockets if you\'re sitting on a train or in any other place with lots of people.',
  'Spain may not be the most budget friendly travel destination, but it\'s still not too bad. You can find hostels starting from $10 and private hotels starting from $40. Meals are about $5 to $10 depending on location. Transportation is generally by bus or train, and these are efficient and great for longer distance trips. The train system may seem a bit complex at first, but it gets easier as you go.'),
  (21,'Italy', 'italian', 'Christianity ', 'diverse', 'Mediterranean climate', 'Euro (EUR)', 'Type C/F', 'rome', 'Rome2rio',
'Italy is well-connected to international destinations, and there are several major airports throughout the country. The primary international airports in Italy are Leonardo da Vinci-Fiumicino Airport (FCO) in Rome, Milan Malpensa Airport (MXP) in Milan, and Marco Polo Airport (VCE) in Venice. These airports serve as major hubs for both domestic and international flights.',
'Italy is generally a safe country to visit, with a low crime rate. However, as with any destination, travelers should exercise caution and take basic safety precautions, especially in tourist areas where pickpocketing and petty theft can occur. Its advisable to keep an eye on your belongings and avoid carrying large amounts of cash or valuables with you. In some areas, there may also be a risk of petty crime, such as bag-snatching or theft from cars, so it s best to stay aware of your surroundings and take precautions to keep yourself and your belongings safe.',
'Traveling to Italy can be done on a budget, but costs can vary depending on your travel style and preferences. Accommodations and transportation can be expensive in major cities like Rome and Venice, but there are budget-friendly options available such as hostels, Airbnb rentals, and public transportation. Food can be affordable in Italy if you opt for local street food and trattorias rather than high-end restaurants. Admission to museums and historical sites can add up, but many offer discounted or free admission on certain days of the week. Overall, traveling to Italy on a budget requires some research and planning, but it is definitely possible to enjoy the countrys beauty and culture without breaking the bank.'),

  (20,'France','French','Secular (Religious diversity)', 'Schengen Area rules apply',' Diverse climate ', 'Euro (EUR)','Type C / E ','Paris','Le Monde',
'France is well-connected to international destinations, and it has several major airports that serve as gateways to the country. The primary international airports in France are Charles de Gaulle Airport (CDG) and Orly Airport (ORY) in Paris, as well as Nice Côte d Azur Airport (NCE) in Nice. These airports are major hubs for both domestic and international flights.',
'France is generally a safe country for travelers, but like any popular tourist destination, it\'s important to take certain precautions. In major cities and tourist areas, pickpocketing and petty theft can occur, so it\'s advisable to remain vigilant and keep an eye on your belongings. Avoid displaying valuable items openly and be cautious in crowded places, such as public transportation or popular attractions. It\'s also recommended to be aware of your surroundings, especially during evening hours, and to stay in well-lit and populated areas. In case of an emergency, familiarize yourself with the local emergency numbers. While the majority of visitors to France have a safe and enjoyable experience, it\'s always prudent to exercise common sense and take appropriate measures to ensure your personal safety and security.',
'Traveling to France can be done on a budget, but costs can vary depending on your choices and preferences. Accommodations, especially in major cities like Paris, can be expensive, but there are budget-friendly options such as hostels, budget hotels, or vacation rentals. Public transportation, like buses and trains, is generally affordable and convenient for getting around within and between cities. Dining in local cafes and brasseries can provide a more cost-effective option compared to high-end restaurants. Additionally, taking advantage of free or discounted attractions, like museums on certain days or city walking tours, can help keep costs down. With careful planning and budgeting, it is possible to explore the beauty of France without breaking the bank.');